include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "test/*"
    - "lib/l10n/messages_*"
  errors:
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    avoid_catches_without_on_clauses: ignore
    prefer_int_literals: ignore
    no_default_cases: ignore
    avoid_classes_with_only_static_members: ignore
    sort_pub_dependencies: ignore
